<?php

namespace Circulo\VegaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AtencionesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AtencionesRepository extends EntityRepository
{
}
