<?php

namespace Circulo\VegaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PracticasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PracticasRepository extends EntityRepository
{
}
