homepage:
    pattern:  /
    defaults: { _controller: VegaBundle:Frontend:index }

_sistema:
    resource: "@VegaBundle/Resources/config/routing.yml"
    prefix:   /sistema

_sonata:
    resource: routing_sonata.yml

sonata_gallery:
    resource: '@SonataMediaBundle/Resources/config/routing/gallery.xml'
    prefix: /media/gallery

sonata_media:
    resource: '@SonataMediaBundle/Resources/config/routing/media.xml'
    prefix: /media
